# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
dist: trusty
cache: packages
latex: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install curl
        - brew link --force curl

before_install:
  - mkdir "/home/travis/netlogo"
  - wget -qO- "https://ccl.northwestern.edu/netlogo/6.0.3/NetLogo-6.0.3-64.tgz" | tar xvz --directory "/home/travis/netlogo"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
  on_success: change
on_failure: change
